/**
 * Build pipeline for `@tksh/svg2ui8a` (engineering-playbook §2, task.md §16).
 *
 *  1. Compiles the two Wasm crates via `wasm-pack --target web`.
 *  2. Copies the Wasm binaries to `assets/`.
 *  3. Regenerates `src/svg2usvg.ts`, `src/svg2rgba.ts`, and `src/mod.ts`
 *     from the wasm-pack glue, embedding the Wasm bytes as base64 and calling
 *     the wasm-bindgen `__wbg_init` with those bytes — no runtime fetch
 *     (`constitution` §3.8, `AGENTS.md` §5.2).
 *  4. Verifies the two artifacts are independent Wasm modules
 *     (`constitution` §3.9, two independently-loadable capabilities).
 *  5. Runs the CDN-free check; aborts the build on failure.
 *
 * wasm-pack 0.15.0 is the recorded toolchain version for this script.
 */

import { runCheck } from "./check-cdn-free.ts";

const resolve = (relativePath: string): string =>
  new URL(relativePath, import.meta.url).pathname;
const ROOT = resolve("../");
const ASSETS_DIR = resolve("../assets/");

/** Run a command from `cwd`, returning trimmed stdout; throws on failure. */
function run(argv: string[], cwd = ROOT): string {
  const [cmd, ...args] = argv;
  const res = new Deno.Command(cmd, {
    args,
    cwd,
    stdout: "piped",
    stderr: "piped",
  }).outputSync();
  if (!res.success) {
    const stderr = new TextDecoder().decode(res.stderr);
    throw new Error(`command failed: ${cmd} ${args.join(" ")}\n${stderr}`);
  }
  return new TextDecoder().decode(res.stdout).trim();
}

const BASE64_ALPHABET =
  "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

/**
 * Encode bytes as RFC 4648 base64. Implemented by hand rather than with
 * chunked `btoa` calls so the `=` padding appears only at the very end (a
 * chunked encoding emits mid-stream padding that `atob` rejects).
 */
function base64(bytes: Uint8Array): string {
  let out = "";
  for (let i = 0; i < bytes.length; i += 3) {
    const b0 = bytes[i];
    const b1 = i + 1 < bytes.length ? bytes[i + 1] : 0;
    const b2 = i + 2 < bytes.length ? bytes[i + 2] : 0;
    out += BASE64_ALPHABET[b0 >> 2] +
      BASE64_ALPHABET[((b0 & 3) << 4) | (b1 >> 4)];
    out += i + 1 < bytes.length
      ? BASE64_ALPHABET[((b1 & 15) << 2) | (b2 >> 6)]
      : "=";
    out += i + 2 < bytes.length ? BASE64_ALPHABET[b2 & 63] : "=";
  }
  return out;
}

/**
 * Inline wasm-pack glue so the generated wrapper is self-contained: strip the
 * module header and final export line, and apply the given renames so the
 * glue's symbols never collide with the public API.
 */
function inlineGlue(glue: string, renames: Array<[string, string]>): string {
  let out = glue.replace(/^\/\* @ts-self-types=.*\*\/\s*/, "");
  for (const [from, to] of renames) {
    out = out.replaceAll(from, to);
  }
  return out.replace(/export \{ initSync, __wbg_init as default \};\s*$/, "");
}

const GENERATED_HEADER = "// deno-fmt-ignore-file\n" +
  "// deno-lint-ignore-file\n" +
  "// @ts-nocheck\n" +
  "/* This file is auto-generated by `scripts/build.ts` — do not edit by hand. */\n\n";

const SVG2USVG_MODULE_DOC = `/**
 * Converts an SVG string into normalized usvg XML bytes.
 *
 * The sole export is {@linkcode svg2usvg}, which parses a supported SVG with
 * feature-disabled \`usvg\` and serializes it with the default \`XmlOptions\`.
 * Every payload is a \`Uint8Array\`; the output is UTF-8 encoded standard SVG
 * XML, not a proprietary binary format.
 *
 * @module
 */

`;

const SVG2RGBA_MODULE_DOC = `/**
 * Renders an SVG string to raw RGBA pixels in one shot.
 *
 * Exports {@linkcode svg2rgba} together with the {@linkcode Svg2RgbaOptions}
 * and {@linkcode RgbaResult} types. The output is a \`Uint8Array\` of packed,
 * row-major RGBA bytes; this module never encodes PNG, WebP, or JPEG.
 *
 * @module
 */

`;

const BASE64_HELPER = `let initialized = false;

function base64ToBytes(b64: string): Uint8Array {
  const binary = atob(b64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

`;

function generateSvg2usvgTs(glue: string, wasm: Uint8Array): string {
  const inlined = inlineGlue(glue, [
    ["export function svg2usvg(svg) {", "function __wasm_svg2usvg(svg) {"],
  ]);
  return GENERATED_HEADER +
    SVG2USVG_MODULE_DOC +
    inlined +
    "\n" +
    `const WASM_BASE64 = ${JSON.stringify(base64(wasm))};\n\n` +
    BASE64_HELPER +
    `/**
 * Parses an SVG document and returns its normalized usvg XML as UTF-8 bytes.
 *
 * The bytes are produced by feature-disabled \`usvg\` with the default
 * \`XmlOptions\` (minimal, deterministic, no pretty-print). They are standard
 * SVG XML, not a proprietary binary format, and re-parse with
 * \`usvg::Tree::from_str\`.
 *
 * @param svg The SVG source to normalize.
 * @returns A promise resolving to the UTF-8 encoded normalized SVG XML.
 * @throws If the SVG cannot be parsed, or if it uses unsupported \`<text>\` or
 * \`<image>\` content.
 *
 * @example Normalize an SVG
 * \`\`\`ts
 * import { svg2usvg } from "@tksh/svg2ui8a/svg2usvg";
 *
 * const xml = await svg2usvg('<svg xmlns="http://www.w3.org/2000/svg"/>');
 * console.log(new TextDecoder().decode(xml));
 * \`\`\`
 */
export async function svg2usvg(svg: string): Promise<Uint8Array> {
  if (!initialized) {
    await __wbg_init({ module_or_path: base64ToBytes(WASM_BASE64) });
    initialized = true;
  }
  return __wasm_svg2usvg(svg);
}
`;
}

function generateSvg2RgbaTs(glue: string, wasm: Uint8Array): string {
  const inlined = inlineGlue(glue, [
    ["RgbaResult", "__wasm_RgbaResult"],
    ["Svg2RgbaOptions", "__wasm_Svg2RgbaOptions"],
    [
      "export function svg2rgba(svg, options) {",
      "function __wasm_svg2rgba(svg, options) {",
    ],
    ["export class ", "class "],
  ]);
  return GENERATED_HEADER +
    SVG2RGBA_MODULE_DOC +
    inlined +
    "\n" +
    `const WASM_BASE64 = ${JSON.stringify(base64(wasm))};\n\n` +
    `/**
 * Options controlling how {@linkcode svg2rgba} rasterizes an SVG.
 */
export interface Svg2RgbaOptions {
  /** Target output width in pixels. Omitted, the natural SVG width is used. */
  width?: number;
  /** Target output height in pixels. Omitted, the natural SVG height is used. */
  height?: number;
  /**
   * Alpha representation of the returned pixels. \`"straight"\` (the default)
   * returns non-premultiplied channels; \`"premultiplied"\` returns the bytes as
   * \`tiny-skia\` produced them.
   */
  alphaMode?: "straight" | "premultiplied";
}

/**
 * The result of a {@linkcode svg2rgba} render.
 */
export interface RectF {
  /** X position in canvas coordinates, mirroring \`usvg::Rect::x()\`. */
  x: number;
  /** Y position in canvas coordinates, mirroring \`usvg::Rect::y()\`. */
  y: number;
  /** Box width, mirroring \`usvg::Rect::width()\`. */
  width: number;
  /** Box height, mirroring \`usvg::Rect::height()\`. */
  height: number;
}

/**
 * The result of a {@linkcode svg2rgba} render.
 */
export interface RgbaResult {
  /** Actual output width in pixels after options were applied. */
  width: number;
  /** Actual output height in pixels after options were applied. */
  height: number;
  /** Natural SVG width before output sizing, in SVG user units. */
  naturalWidth: number;
  /** Natural SVG height before output sizing, in SVG user units. */
  naturalHeight: number;
  /** Alpha mode of the pixels: \`"straight"\` or \`"premultiplied"\`. */
  alphaMode: string;
  /**
   * Raw RGBA pixels: one pixel per four bytes, row-major, top-to-bottom. The
   * length is \`width * height * 4\`.
   */
  pixels: Uint8Array;
  /**
   * Upstream \`usvg::Group::abs_bounding_box()\` of the parsed document root,
   * in canvas coordinates. \`null\` only when the measurement is unavailable;
   * zero-area boxes pass through verbatim.
   */
  absBoundingBox: RectF | null;
  /**
   * Upstream \`usvg::Group::abs_stroke_bounding_box()\` of the parsed document
   * root, in canvas coordinates. \`null\` only when unavailable.
   */
  absStrokeBoundingBox: RectF | null;
  /**
   * Upstream \`usvg::Group::abs_layer_bounding_box()\` of the parsed document
   * root, in canvas units. \`null\` only when unavailable; upstream returns
   * \`0,0,1,1\` for empty groups.
   */
  absLayerBoundingBox: RectF | null;
}

` +
    BASE64_HELPER +
    `/**
 * Parses an SVG document and renders it to raw RGBA pixels in one shot.
 *
 * There is no intermediate payload and no cacheable-bytes contract beyond
 * "same input, same pixels". The canvas is fully transparent outside the
 * painted shapes.
 *
 * @param svg The SVG source to render.
 * @param options Optional sizing and alpha-mode controls.
 * @returns A promise resolving to the rendered pixels and their dimensions.
 * @throws If the SVG cannot be parsed, uses unsupported \`<text>\` or
 * \`<image>\` content, requests invalid dimensions, has a zero natural size, or
 * exhausts Wasm linear memory.
 *
 * @example Render an SVG to pixels
 * \`\`\`ts
 * import { svg2rgba } from "@tksh/svg2ui8a/svg2rgba";
 *
 * const { pixels, width, height } = await svg2rgba(
 *   '<svg xmlns="http://www.w3.org/2000/svg" width="1" height="1"/>',
 * );
 * console.log(width, height, pixels.length);
 * \`\`\`
 */
export async function svg2rgba(
  svg: string,
  options?: Svg2RgbaOptions,
): Promise<RgbaResult> {
  if (!initialized) {
    await __wbg_init({ module_or_path: base64ToBytes(WASM_BASE64) });
    initialized = true;
  }
  const opts = new __wasm_Svg2RgbaOptions();
  opts.width = options?.width ?? 0;
  opts.height = options?.height ?? 0;
  opts.alpha_mode = options?.alphaMode ?? "straight";
  const result = __wasm_svg2rgba(svg, opts);
  const rectOrNull = (
    x: number | undefined,
    y: number | undefined,
    width: number | undefined,
    height: number | undefined,
  ): RectF | null =>
    x != null && y != null && width != null && height != null
      ? { x, y, width, height }
      : null;
  try {
    return {
      width: result.width,
      height: result.height,
      naturalWidth: result.natural_width,
      naturalHeight: result.natural_height,
      alphaMode: result.alpha_mode,
      pixels: result.pixels,
      absBoundingBox: rectOrNull(
        result.abs_bounding_box_x,
        result.abs_bounding_box_y,
        result.abs_bounding_box_width,
        result.abs_bounding_box_height,
      ),
      absStrokeBoundingBox: rectOrNull(
        result.abs_stroke_bounding_box_x,
        result.abs_stroke_bounding_box_y,
        result.abs_stroke_bounding_box_width,
        result.abs_stroke_bounding_box_height,
      ),
      absLayerBoundingBox: rectOrNull(
        result.abs_layer_bounding_box_x,
        result.abs_layer_bounding_box_y,
        result.abs_layer_bounding_box_width,
        result.abs_layer_bounding_box_height,
      ),
    };
  } finally {
    result.free();
  }
}
`;
}

function generateModTs(): string {
  return `/**
 * \`@tksh/svg2ui8a\`: turns SVG strings into \`Uint8Array\` payloads.
 *
 * Re-exports the two public functions and their supporting types. Import the
 * subpaths \`@tksh/svg2ui8a/svg2usvg\` or \`@tksh/svg2ui8a/svg2rgba\` to load
 * only the capability you need.
 *
 * @module
 */
export { svg2rgba } from "./svg2rgba.ts";
export type { RgbaResult, Svg2RgbaOptions } from "./svg2rgba.ts";
export { svg2usvg } from "./svg2usvg.ts";
`;
}

function verifyWasmExports(): void {
  const modules = Object.fromEntries(
    ["svg2usvg", "svg2rgba"].map((crate) => {
      const mod = new WebAssembly.Module(
        Deno.readFileSync(resolve(`../assets/${crate}_bg.wasm`)),
      );
      return [crate, WebAssembly.Module.exports(mod).map((e) => e.name)];
    }),
  );

  for (
    const [crate, expected] of [
      ["svg2usvg", "svg2usvg"],
      ["svg2rgba", "svg2rgba"],
    ] as const
  ) {
    if (!modules[crate].includes(expected)) {
      throw new Error(`${crate}_bg.wasm is missing the ${expected} export`);
    }
    for (const other of ["svg2usvg", "svg2rgba"]) {
      if (other !== expected && modules[crate].includes(other)) {
        throw new Error(`${crate}_bg.wasm contains the ${other} export`);
      }
    }
  }
  console.log("  ✓ two independent Wasm artifacts confirmed");
}

function main(): void {
  Deno.mkdirSync(ASSETS_DIR, { recursive: true });

  console.log(
    `wasm-pack ${run(["wasm-pack", "--version"]).replace("wasm-pack ", "")}`,
  );

  for (const crate of ["svg2rgba", "svg2usvg"]) {
    console.log(`Building ${crate} Wasm...`);
    run([
      "wasm-pack",
      "build",
      resolve(`../crates/${crate}`),
      "--target",
      "web",
    ]);
    Deno.copyFileSync(
      resolve(`../crates/${crate}/pkg/${crate}_bg.wasm`),
      resolve(`../assets/${crate}_bg.wasm`),
    );
    console.log(`  → copied to assets/${crate}_bg.wasm`);
  }

  console.log("Regenerating TypeScript wrappers...");
  Deno.writeTextFileSync(
    resolve("../src/svg2usvg.ts"),
    generateSvg2usvgTs(
      Deno.readTextFileSync(resolve("../crates/svg2usvg/pkg/svg2usvg.js")),
      Deno.readFileSync(resolve("../crates/svg2usvg/pkg/svg2usvg_bg.wasm")),
    ),
  );
  Deno.writeTextFileSync(
    resolve("../src/svg2rgba.ts"),
    generateSvg2RgbaTs(
      Deno.readTextFileSync(resolve("../crates/svg2rgba/pkg/svg2rgba.js")),
      Deno.readFileSync(resolve("../crates/svg2rgba/pkg/svg2rgba_bg.wasm")),
    ),
  );
  Deno.writeTextFileSync(resolve("../src/mod.ts"), generateModTs());
  console.log(
    "  → wrote src/svg2usvg.ts, src/svg2rgba.ts, src/mod.ts",
  );

  verifyWasmExports();

  runCheck();
  console.log("Build complete.");
}

if (import.meta.main) {
  main();
}
