/**
 * Build pipeline for `@tksh/svg2ui8a` (engineering-playbook §2, task.md §5,
 * rename plan Phases 2–3).
 *
 *  1. Compiles all three Wasm crates via `wasm-pack --target web`.
 *  2. Copies the Wasm binaries to `assets/`.
 *  3. Regenerates `src/stln.ts`, `src/stln-rgba.ts`, `src/svg2rgba.ts`, and
 *     `src/mod.ts` from the wasm-pack glue, embedding the Wasm bytes as
 *     base64 and calling the wasm-bindgen `__wbg_init` with those bytes — no
 *     runtime fetch (`constitution` §3.8, `AGENTS.md` §5.2).
 *  4. Verifies the three artifacts are independent Wasm modules
 *     (`constitution` §3.9, as amended for three independently-loadable
 *     capabilities).
 *  5. Runs the CDN-free check; aborts the build on failure.
 *
 * wasm-pack 0.15.0 is the recorded toolchain version for this script.
 */

import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { runCheck } from "./check-cdn-free.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const ASSETS_DIR = join(ROOT, "assets");
const SRC_DIR = join(ROOT, "src");
const CARGO_DIR = join(ROOT, "crates");

/** Run a command from `cwd`, returning trimmed stdout; throws on failure. */
function run(argv: string[], cwd = ROOT): string {
  const [cmd, ...args] = argv;
  const res = new Deno.Command(cmd, {
    args,
    cwd,
    stdout: "piped",
    stderr: "piped",
  }).outputSync();
  if (!res.success) {
    const stderr = new TextDecoder().decode(res.stderr);
    throw new Error(`command failed: ${cmd} ${args.join(" ")}\n${stderr}`);
  }
  return new TextDecoder().decode(res.stdout).trim();
}

const BASE64_ALPHABET =
  "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

/**
 * Encode bytes as RFC 4648 base64. Implemented by hand rather than with
 * chunked `btoa` calls so the `=` padding appears only at the very end (a
 * chunked encoding emits mid-stream padding that `atob` rejects).
 */
function base64(bytes: Uint8Array): string {
  let out = "";
  for (let i = 0; i < bytes.length; i += 3) {
    const b0 = bytes[i];
    const b1 = i + 1 < bytes.length ? bytes[i + 1] : 0;
    const b2 = i + 2 < bytes.length ? bytes[i + 2] : 0;
    out += BASE64_ALPHABET[b0 >> 2] +
      BASE64_ALPHABET[((b0 & 3) << 4) | (b1 >> 4)];
    out += i + 1 < bytes.length
      ? BASE64_ALPHABET[((b1 & 15) << 2) | (b2 >> 6)]
      : "=";
    out += i + 2 < bytes.length ? BASE64_ALPHABET[b2 & 63] : "=";
  }
  return out;
}

/**
 * Inline wasm-pack glue so the generated wrapper is self-contained: strip the
 * module header and final export line, and apply the given renames so the
 * glue's symbols never collide with the public API.
 */
function inlineGlue(glue: string, renames: Array<[string, string]>): string {
  let out = glue.replace(/^\/\* @ts-self-types=.*\*\/\s*/, "");
  for (const [from, to] of renames) {
    out = out.replaceAll(from, to);
  }
  return out.replace(/export \{ initSync, __wbg_init as default \};\s*$/, "");
}

const GENERATED_HEADER = "// deno-fmt-ignore-file\n" +
  "// deno-lint-ignore-file\n" +
  "// @ts-nocheck\n" +
  "/* This file is auto-generated by `scripts/build.ts` — do not edit by hand. */\n\n";

const BASE64_HELPER = `let initialized = false;

function base64ToBytes(b64: string): Uint8Array {
  const binary = atob(b64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

`;

function generateStlnTs(glue: string, wasm: Uint8Array): string {
  const inlined = inlineGlue(glue, [
    ["export function svg2stln(svg) {", "function __wasm_svg2stln(svg) {"],
  ]);
  return GENERATED_HEADER +
    inlined +
    "\n" +
    `const WASM_BASE64 = ${JSON.stringify(base64(wasm))};\n\n` +
    BASE64_HELPER +
    `export async function svg2stln(svg: string): Promise<Uint8Array> {
  if (!initialized) {
    await __wbg_init({ module_or_path: base64ToBytes(WASM_BASE64) });
    initialized = true;
  }
  return __wasm_svg2stln(svg);
}
`;
}

function generateStlnRgbaTs(glue: string, wasm: Uint8Array): string {
  const inlined = inlineGlue(glue, [
    ["RgbaResult", "__wasm_RgbaResult"],
    ["Stln2RgbaOptions", "__wasm_Stln2RgbaOptions"],
    [
      "export function stln2rgba(usvg, options) {",
      "function __wasm_stln2rgba(usvg, options) {",
    ],
    ["export class ", "class "],
  ]);
  return GENERATED_HEADER +
    inlined +
    "\n" +
    `const WASM_BASE64 = ${JSON.stringify(base64(wasm))};\n\n` +
    `export interface Stln2RgbaOptions {
  width?: number;
  height?: number;
  alphaMode?: "straight" | "premultiplied";
}

export interface RgbaResult {
  width: number;
  height: number;
  alphaMode: string;
  pixels: Uint8Array;
}

` +
    BASE64_HELPER +
    `export async function stln2rgba(
  usvg: Uint8Array,
  options?: Stln2RgbaOptions,
): Promise<RgbaResult> {
  if (!initialized) {
    await __wbg_init({ module_or_path: base64ToBytes(WASM_BASE64) });
    initialized = true;
  }
  const opts = new __wasm_Stln2RgbaOptions();
  opts.width = options?.width ?? 0;
  opts.height = options?.height ?? 0;
  opts.alpha_mode = options?.alphaMode ?? "straight";
  const result = __wasm_stln2rgba(usvg, opts);
  return {
    width: result.width,
    height: result.height,
    alphaMode: result.alpha_mode,
    pixels: result.pixels,
  };
}
`;
}

function generateSvg2RgbaTs(glue: string, wasm: Uint8Array): string {
  const inlined = inlineGlue(glue, [
    ["RgbaResult", "__wasm_RgbaResult"],
    ["Svg2RgbaOptions", "__wasm_Svg2RgbaOptions"],
    [
      "export function svg2rgba(svg, options) {",
      "function __wasm_svg2rgba(svg, options) {",
    ],
    ["export class ", "class "],
  ]);
  return GENERATED_HEADER +
    inlined +
    "\n" +
    `const WASM_BASE64 = ${JSON.stringify(base64(wasm))};\n\n` +
    `export interface Svg2RgbaOptions {
  width?: number;
  height?: number;
  alphaMode?: "straight" | "premultiplied";
}

export interface RgbaResult {
  width: number;
  height: number;
  alphaMode: string;
  pixels: Uint8Array;
}

` +
    BASE64_HELPER +
    `export async function svg2rgba(
  svg: string,
  options?: Svg2RgbaOptions,
): Promise<RgbaResult> {
  if (!initialized) {
    await __wbg_init({ module_or_path: base64ToBytes(WASM_BASE64) });
    initialized = true;
  }
  const opts = new __wasm_Svg2RgbaOptions();
  opts.width = options?.width ?? 0;
  opts.height = options?.height ?? 0;
  opts.alpha_mode = options?.alphaMode ?? "straight";
  const result = __wasm_svg2rgba(svg, opts);
  return {
    width: result.width,
    height: result.height,
    alphaMode: result.alpha_mode,
    pixels: result.pixels,
  };
}
`;
}

function generateModTs(): string {
  return `/**
 * Re-exports the public functions and types from the svg2ui8a package.
 * Regenerated by \`scripts/build.ts\`; content is the hand-maintained surface.
 */
export { svg2rgba } from "./svg2rgba.ts";
export type { Svg2RgbaOptions } from "./svg2rgba.ts";
export { svg2stln } from "./stln.ts";
export { stln2rgba } from "./stln-rgba.ts";
export type { RgbaResult, Stln2RgbaOptions } from "./stln-rgba.ts";
`;
}

function verifyWasmExports(): void {
  const modules = Object.fromEntries(
    ["svg2stln", "stln2rgba", "svg2rgba"].map((crate) => {
      const mod = new WebAssembly.Module(
        Deno.readFileSync(join(ASSETS_DIR, `${crate}_bg.wasm`)),
      );
      return [crate, WebAssembly.Module.exports(mod).map((e) => e.name)];
    }),
  );

  for (
    const [crate, expected] of [
      ["svg2stln", "svg2stln"],
      ["stln2rgba", "stln2rgba"],
      ["svg2rgba", "svg2rgba"],
    ] as const
  ) {
    if (!modules[crate].includes(expected)) {
      throw new Error(`${crate}_bg.wasm is missing the ${expected} export`);
    }
    for (const other of ["svg2stln", "stln2rgba", "svg2rgba"]) {
      if (other !== expected && modules[crate].includes(other)) {
        throw new Error(`${crate}_bg.wasm contains the ${other} export`);
      }
    }
  }
  console.log("  ✓ three independent Wasm artifacts confirmed");
}

function main(): void {
  Deno.mkdirSync(ASSETS_DIR, { recursive: true });

  console.log(
    `wasm-pack ${run(["wasm-pack", "--version"]).replace("wasm-pack ", "")}`,
  );

  for (const crate of ["svg2rgba", "svg2stln", "stln2rgba"]) {
    console.log(`Building ${crate} Wasm...`);
    run(["wasm-pack", "build", join(CARGO_DIR, crate), "--target", "web"]);
    Deno.copyFileSync(
      join(CARGO_DIR, crate, "pkg", `${crate}_bg.wasm`),
      join(ASSETS_DIR, `${crate}_bg.wasm`),
    );
    console.log(`  → copied to assets/${crate}_bg.wasm`);
  }

  console.log("Regenerating TypeScript wrappers...");
  Deno.writeTextFileSync(
    join(SRC_DIR, "stln.ts"),
    generateStlnTs(
      Deno.readTextFileSync(join(CARGO_DIR, "svg2stln", "pkg", "svg2stln.js")),
      Deno.readFileSync(join(CARGO_DIR, "svg2stln", "pkg", "svg2stln_bg.wasm")),
    ),
  );
  Deno.writeTextFileSync(
    join(SRC_DIR, "stln-rgba.ts"),
    generateStlnRgbaTs(
      Deno.readTextFileSync(
        join(CARGO_DIR, "stln2rgba", "pkg", "stln2rgba.js"),
      ),
      Deno.readFileSync(
        join(CARGO_DIR, "stln2rgba", "pkg", "stln2rgba_bg.wasm"),
      ),
    ),
  );
  Deno.writeTextFileSync(
    join(SRC_DIR, "svg2rgba.ts"),
    generateSvg2RgbaTs(
      Deno.readTextFileSync(join(CARGO_DIR, "svg2rgba", "pkg", "svg2rgba.js")),
      Deno.readFileSync(join(CARGO_DIR, "svg2rgba", "pkg", "svg2rgba_bg.wasm")),
    ),
  );
  Deno.writeTextFileSync(join(SRC_DIR, "mod.ts"), generateModTs());
  console.log(
    "  → wrote src/stln.ts, src/stln-rgba.ts, src/svg2rgba.ts, src/mod.ts",
  );

  verifyWasmExports();

  runCheck();
  console.log("Build complete.");
}

if (import.meta.main) {
  main();
}
