/**
 * Re-exports the two public functions and types from the svg2ui8a package.
 * Regenerated by `scripts/build.ts`; content is the hand-maintained surface.
 */
export { svg2usvg } from "./usvg.ts";
export { usvg2rgba } from "./rgba.ts";
export type { RgbaResult, Usvg2RgbaOptions } from "./rgba.ts";
