/**
 * Re-exports the public functions and types from the svg2ui8a package.
 * Regenerated by `scripts/build.ts`; content is the hand-maintained surface.
 */
export { svg2rgba } from "./svg2rgba.ts";
export type { RgbaResult, Svg2RgbaOptions } from "./svg2rgba.ts";
export { svg2usvg } from "./svg2usvg.ts";
