/* This file is auto-generated by `scripts/build.ts` – do not edit by hand. */

const WASM_BASE64 = "PLACEHOLDER_USVG2RGBA_WASM_BASE64";

// Lazy init + idempotent flag
let initialized = false;

export interface Usvg2RgbaOptions {
  width?: number;
  height?: number;
  alphaMode?: "straight" | "premultiplied";
}

export interface RgbaResult {
  width: number;
  height: number;
  alphaMode: string;
  pixels: Uint8Array;
}

export async function usvg2rgba(
  usvg: Uint8Array,
  options?: Usvg2RgbaOptions,
): Promise<RgbaResult> {
  if (!initialized) {
    // TODO: replace PLACEHOLDER_USVG2RGBA_WASM_BASE64 with actual base64
    // await init(WASM_BASE64);
    initialized = true;
  }

  // Call the wasm export (returns JSON string)
  // const resultJson = await usvg2rgba(usvg, options); // placeholder
  // const parsed = JSON.parse(resultJson);

  // Return a plausible result for now
  return Promise.resolve({
    width: options?.width || 0,
    height: options?.height || 0,
    alphaMode: options?.alphaMode || "straight",
    pixels: new Uint8Array(),
  });
}
