/* This file is auto-generated by `scripts/build.ts` – do not edit by hand. */

const WASM_BASE64 = "PLACEHOLDER_SVG2USVG_WASM_BASE64";

// Lazy init + idempotent flag
let initialized = false;

export async function svg2usvg(svg: string): Promise<Uint8Array> {
  if (!initialized) {
    // Note: in a real build, PLACEHOLDER_SVG2USVG_WASM_BASE64 is replaced
    // by the build script with the actual base64-encoded wasm bytes.
    // The wasm-bindgen init function accepts a BufferSource.
    // await init(WASM_BASE64); // TODO: replace placeholder
    initialized = true;
  }

  // Call the wasm export (sync, returns JSON string)
  // const result = await svg2usvg(svg); // placeholder
  // Return a resolved promise with a placeholder Uint8Array for now
  return Promise.resolve(new Uint8Array([0, 0, 0, 0]));
}
